WIP avc3
membraneframework/membrane_mp4_plugin pull request #113
Opened 2024-06-06 14:09 UTC by mat-hek

2024-08-07 14:05 UTC, varsill requested changes

2024-08-07 14:05 UTC, varsill commented on lib/membrane_mp4/demuxer/isom.ex
> +          stream_structure: {_avc, _dcr},
We should assert on `_avc` being either `:avc1` or `:avc3`

2024-08-07 14:05 UTC, varsill commented on lib/membrane_mp4/muxer/isom.ex
> +      previos_format ->
```suggestion
      previous_format ->
```

2024-08-07 14:05 UTC, varsill commented on lib/membrane_mp4/muxer/isom.ex
> +      %^type{} ->
Is it OK for us to accept change from `:avc3` to `:avc1`? Wouldn't it require appending something to the DCR?

2024-08-07 14:05 UTC, varsill commented on test/membrane_mp4/muxer/isom/integration_test.exs
> -  describe "ctts table" do
Why have you removed this test?

2024-08-07 16:04 UTC, mat-hek commented on test/membrane_mp4/muxer/isom/integration_test.exs
> -  describe "ctts table" do
ups :P

2024-08-22 09:40 UTC, varsill requested changes

2024-08-22 09:40 UTC, varsill commented on lib/membrane_mp4/muxer/isom.ex
> +      {%Membrane.H265{}, %Membrane.H265{}} ->
I believe you should check for: 
```suggestion
      {%Membrane.H265{stream_structure: {:hev1, _dcr1}}, %Membrane.H265{stream_structure: {:hev1, _dcr2}}} ->
```

2024-08-22 10:48 UTC, varsill approved these changes
🥇

2024-08-22 14:44 UTC, merged